### ISSUE TITLE
ffff

### ISSUE THREAD

**Issue by Skytekrp** [Skytekrp/FlowAutomate#3]
```yaml
---
lz_id: SaftInoxASNonProd
application_rules:
  - description: saft git repo
    comment: deploy webapps code from git repository saft.mytuleap.com
    target_fqdns:
      - saft.mytuleap.com
    protocol_port:
      - Https
  - description: drupal update
    comment: update drupal package from package.drupal.org
    target_fqdns:
      - packages.drupal.org
    protocol_port:
      - Https
  - description: microsoft oryx
    comment: oryx apps service build
    target_fqdns:
      - oryx-cdn.microsoft.io
    protocol_port:
      - Https
  - description: api github mod
    comment: api github modules drupal
    target_fqdns:
      - api.github.com
    protocol_port:
      - Https
  - description: saft unipass
    comment: access to unipass authentification service
    target_fqdns:
      - sis.saftbatteries.com
    protocol_port:
      - Https
  - description: saft matomo
    comment: access to saft statistics tool
    target_fqdns:
      - webstatt.saftbatteries.com
    protocol_port:
      - Https
  - description: codeload github
    comment: access to codeload github to install sympfony packages
    target_fqdns:
      - codeload.github.com
    protocol_port:
      - Https
  - description: ftp drupal mod
    comment: access to ftp drupal modules
    target_fqdns:
      - ftp.drupal.org
    protocol_port:
      - Https
  - description: bootstrap
    comment: access to drupal bootstrap gitlab source
    target_fqdns:
      - git.drupalcode.org
    protocol_port:
      - Https
  - description: update drupal
    comment: access to update drupal website
    target_fqdns:
      - updates.drupal.org
    protocol_port:
      - Https
  - description: composer
    comment: access to run composer drupal
    target_fqdns:
      - repo.packagist.org
    protocol_port:
      - Https
  - description: jsdeliver
    comment: retrieve CSS and js
    target_fqdns:
      - cdn.jsdeliver.net
    protocol_port:
      - Https
  - description: CRM NonProd
    comment: Dynamics NonProd
    target_fqdns:
      - testcustomer360.crm4.dynamics.com
    protocol_port:
      - Https
  - description: Dynamics Non-Prod api
    comment: Dynamics Non-Prod api
    target_fqdns:
      - testcustomer360.api.crm4.dynamics.com
    protocol_port:
      - Https
  - description: Google et github
    comment: Google et github
    target_fqdns:
      - google.com
      - github.com 
    protocol_port:
      - Https
  - description: regisytry npmjs
    comment: 
    target_fqdns:
      - registry.npmjs.org
    protocol_port:
      - Https

```
